analyzer:
  errors:
    todo: ignore
  exclude:
    - flutter/**

linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - unnecessary_const
    - unnecessary_new